name: Run Tests

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: NPM install
        run: |
          npm ci

      - name: Run Tests
        run: |
          npm run test:ci
          pwd
          ls -al coverage

      - name: Upload Coverage to the Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "coverage"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
